version: '3'

services:
  utility:
    image: buzzingpixel/utility:1.1.0
    container_name: utility-corbomite-db
    environment:
      HOSTNAME: utility-corbomite-db
    volumes:
      - .:/app
      - db-volume:/db-volume
    command: bash -c "chmod +x /app/scripts/devUtilityScript.sh && /app/scripts/devUtilityScript.sh"
  php:
    image: buzzingpixel/php7.2:1.0.6
    container_name: php-corbomite-db
    environment:
      HOSTNAME: php-corbomite-http
      COMPOSER_HOME: /composer-home-volume
    volumes:
      - .:/app:delegated
      - ./serverConfig/php/php-custom-config.ini:/usr/local/etc/php/conf.d/php-custom-config.ini:delegated
      - ./serverConfig/php/php-config-dev.ini:/usr/local/etc/php/conf.d/php-env-config.ini:delegated
      - composer-home-volume:/composer-home-volume:delegated
  db:
    image: buzzingpixel/mariadb:2.0.1
    container_name: db-corbomite-db
    restart: always
    environment:
      HOSTNAME: db-mission-control
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: site
      MYSQL_DATABASE: site
      MYSQL_PASSWORD: secret
    user: "1000:50"
    volumes:
      - .:/app:delegated
      - db-volume:/var/lib/mysql
    ports:
      - "22649:3306"

volumes:
  composer-home-volume:
  db-volume:
